from .grarep import GraRep
from .deepwalk import DeepWalk
from .node2vec import Node2Vec
from .walklets import Walklets
from .nmfadmm import NMFADMM
from .diff2vec import Diff2Vec
from .boostne import BoostNE
from .netmf import NetMF
from .laplacianeigenmaps import LaplacianEigenmaps
from .hope import HOPE
from .nodesketch import NodeSketch
