from .grarep import GraRep
from .deepwalk import DeepWalk
from .walklets import Walklets
from .nmfadmm import NMFADMM
from .diff2vec import Diff2Vec
from .boostne import BoostNE
from .netmf import NetMF
from .laplacianeigenmaps import LaplacianEigenmaps
from .hope import HOPE
from .nodesketch import NodeSketch
